sudo: required
services:
  - docker

before_install:
  - docker build -t kuberizal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kuberizal/docker-react npm run test -- --coverage
